# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'APFeedBack_Example' do

pod "APFeedBack"

end
target 'APFeedBackSwift' do
use_frameworks!
pod "APFeedBack"

end


